[workspace]
authors = ["Sylens Wong <qiumin14@163.com>"]
channels = ["conda-forge"]
name = "rkmpp-recipe"
platforms = ["linux-aarch64", "linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[dependencies]
rattler-build = "*"

[tasks.build]
cmd = "TARGET_PLATFORM={{ platform }} pixi build -t {{ platform }}"
args = ["platform"]
depends-on = [{ task = "bump", args = ["{{ platform }}"] }]

[package.build.backend]
name = "pixi-build-rattler-build"
version = "0.3.*" 